
import { Footer, Navbar } from "@/components/index ";
import "./globals.css";

export const metadata = {
  title: "TechFiesta'24",
  description: "Generated by create next app",
  icons:
  {
    icon: "./favicon.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-3 font-generalsans bg-black text-red">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
