import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer/Footer";


export const metadata = {
  title: "TechFiesta'24",
  description: "Generated by create next app",
  icons:
  {
    icon: "./favicon.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-3" style={{ backgroundColor: '#ffffff' }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
